queue.mem:
  events: ${FILEBEAT_MEM_EVENTS:4096}
  flush.min_events: ${FILEBEAT_MEM_MIN_EVENTS:2048}
  flush.timeout: ${FILEBEAT_MEM_TIMEOUT:1s}

filebeat.inputs:
- type: udp
  max_message_size: ${UDP_MAX_MESSAGE_SIZE:56KiB}
  host: ":${UDP_LISTEN_PORT:5160}"

output.elasticsearch:
  hosts: "${ELASTIC_HOSTS:elasticsearch:9200}"
  protocol: "${ELASTIC_PROTOCOL:http}"
  username: "${ELASTIC_USERNAME:''}"
  password: "${ELASTIC_PASSWORD:''}"
  index: "${ELASTIC_INDEX:filebeat}"

logging:
  metrics:
    enabled: false

processors:
  - decode_json_fields:
      fields: "${PROCESSORS_DECODE_FIELDS:message}"
      process_array: ${PROCESSORS_DECODE_PROCESS_ARRAY:false}
      max_depth: ${PROCESSORS_DECODE_MAX_DEPTH:1}
      target: "${PROCESSORS_DECODE_TARGET:''}"
      overwrite_keys: ${PROCESSORS_DECODE_OVERWRITE_KEYS:false}
  - drop_fields:
      fields: "${PROCESSORS_DROP_FIELDS:message}"

setup.template:
  index: "${ELASTIC_INDEX:filebeat}"
  pattern: "${ELASTIC_INDEX:filebeat}-*"
  enabled: false